dependencies:
  dotenv: ^4.1.0
  http: ^0.13.6
  image: ^4.0.17
  nyxx: ^5.0.3
  nyxx_interactions: ^4.6.0

description: A simple command-line application.

dev_dependencies:
  lints: ^2.0.0

environment:
  sdk: ^3.0.0

name: dcord
repository: https://github.com/TeamXNET/dcord/
version: 1.0.0
